services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paybridge-loan-svc
    ports:
      - "8084:8084"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
#    environment:
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
#      REDIS_HOST: ${REDIS_HOST}
#      REDIS_PORT: ${REDIS_PORT}
#      REDIS_PASSWORD: ${REDIS_PASSWORD}
#      TOKEN_TRANSACTION_SERVICE: ${TOKEN_TRANSACTION_SERVICE}
#      TRANSACTION_SERVICE_ENDPOINT: ${TRANSACTION_SERVICE_ENDPOINT}
#      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
#      JWT_TTL: ${JWT_TTL}
    networks:
      - paybridge_network

networks:
  paybridge_network:
    external: true